//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Account_Game = new HashSet<Account_Game>();
            this.Purchases = new HashSet<Purchases>();
            this.Trading_Platform = new HashSet<Trading_Platform>();
            this.Trading_Platform1 = new HashSet<Trading_Platform>();
        }
    
        public int ID_Account { get; set; }
        public string Name_Account { get; set; }
        public string Email { get; set; }
        public string Registration_Date { get; set; }
        public Nullable<int> Review_ID { get; set; }
        public int Authorization_ID { get; set; }
    
        public virtual Authorization_Table Authorization_Table { get; set; }
        public virtual Reviews Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Game> Account_Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trading_Platform> Trading_Platform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trading_Platform> Trading_Platform1 { get; set; }
    }
}
