//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.Account_Game = new HashSet<Account_Game>();
            this.Items = new HashSet<Items>();
            this.Purchases = new HashSet<Purchases>();
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int ID_Game { get; set; }
        public string Name_Game { get; set; }
        public string Realise_date { get; set; }
        public string Description_Game { get; set; }
        public decimal Price { get; set; }
        public int Developer_ID { get; set; }
        public int Publisher_ID { get; set; }
        public int Tag_ID { get; set; }
        public Nullable<int> Discount_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Game> Account_Game { get; set; }
        public virtual Developers Developers { get; set; }
        public virtual Discounts Discounts { get; set; }
        public virtual Publishers Publishers { get; set; }
        public virtual Tags Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
