//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trading_Platform
    {
        public int ID_Trading_Platform { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Item_ID { get; set; }
        public int Seller_ID { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Items Items { get; set; }
    }
}
